DaFitnessApp/dafitnessapp/urls.py
from django.urls import path

from .import views

app_name = 'dafitnessapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('calculator', views.IndexView.as_view(), name='index'),
    path('daily-calorie-intake', views.ResultsView.as_view(), name='results'),
    path('comments', views.CommentsView.as_view(), name='comments'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('new', views.create_view, name='create'),
]

DaFitnessApp/dafitnessapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class dafitnessapp(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

DaFitnessApp/dafitnessapp/forms.py
from django import forms

from .models import dafitnessapp


class CreateForm(forms.ModelForm):
    class Meta:
        model = dafitnessapp
        fields = ['title', 'text']

DaFitnessApp/dafitnessapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from django.urls import reverse_lazy
from .models import dafitnessapp
from django.contrib.auth.models import User
from .forms import CreateForm


class HomeView(generic.ListView):
    template_name = 'dafitnessapp/home.html'
    context_object_name = 'dafitnessapp_list'

    def get_queryset(self):
        return dafitnessapp.objects.all()


class IndexView(generic.ListView):
    template_name = 'dafitnessapp/index.html'
    context_object_name = 'dafitnessapp_list'

    def get_queryset(self):
        return dafitnessapp.objects.all()


class ResultsView(generic.ListView):
    template_name = 'dafitnessapp/results.html'
    context_object_name = 'dafitnessapp_list'

    def get_queryset(self):
        return dafitnessapp.objects.all()


class CommentsView(generic.ListView):
    template_name = 'dafitnessapp/comments.html'
    context_object_name = 'dafitnessapp_list'

    def get_queryset(self):
        return dafitnessapp.objects.all()


class CreateView(generic.edit.CreateView):
    template_name = 'dafitnessapp/create.html'
    model = dafitnessapp
    fields = ['author', 'title', 'text']
    success_url = reverse_lazy('dafitnessapp:home')


def create_view(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.save()
            return redirect('dafitnessapp:comments')
    else:
        form = CreateForm()
    return render(request, 'dafitnessapp/create.html', {'form': form})


class UpdateView(generic.edit.UpdateView):
    template_name = 'dafitnessapp/update.html'
    model = dafitnessapp
    fields = ['title', 'text']
    success_url = reverse_lazy('dafitnessapp:comments')


class DeleteView(generic.edit.DeleteView):
    template_name = 'dafitnessapp/delete.html'
    model = dafitnessapp
    success_url = reverse_lazy('dafitnessapp:home')

DaFitnessApp/dafitnessapp/templates/dafitnessapp/base.html
<html>
    <head>
        <meta name="viewport" content="with=device-width, initial-scale=1.0">
        <title>Da Fitness App</title>
        <!-- bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <!-- allows dropdown menu to work -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@200;300;400;600;700&display=swap" rel="stylesheet">
        <!-- for the close and open button when opening on a mobile device -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <section class="header">
            <nav class="navbar-custom">
                <a class="title" href="{% url 'dafitnessapp:home' %}">Da Fitness App</a>
                <div class="navbar-nav" id="navLinks">
                    <i class="fa fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="{% url 'dafitnessapp:home' %}">Home</a></li>
                        <li><a href="{% url 'dafitnessapp:index' %}">Calculator</a></li>
                        <li><a href="{% url 'dafitnessapp:results' %}">Daily Calorie Intake</a></li>
                        <li><a href="{% url 'dafitnessapp:comments' %}">Comments/Suggestions</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                {% if user.is_authenticated %}
                                {{request.user}}
                                {% else %}
                                Account
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}" class="ml-2">Log Out</a>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'accounts:login' %}" class="ml-2">Log In</a>
                                <a class="dropdown-item" href="{% url 'accounts:signup' %}" class="ml-2">Sign up</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
                <i class="fa fa-bars" onclick="showMenu()"></i>
            </nav>
            {% block content %}
            {% endblock %}
        </section>
        <script>
            var navLinks = document.getElementById("navLinks");
            function showMenu(){
                navLinks.style.right = "0";
            }
            function hideMenu(){
                navLinks.style.right = "-200px"
            }
        </script>
    </body>
</html>

DaFitnessApp/dafitnessapp/templates/dafitnessapp/comments.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
<html>
    <h1>Comments/Suggestions</h1>
    <p>
        Please feel free to input your opinions about this app below:
    </p>
    <!-- This is where the user can put in their thoughts, while being able to delete or update their messages -->
    {% if user.is_authenticated %}
        <a href="{% url 'dafitnessapp:create' %}">Create a new comment</a>
    {% else %}
    Please <a href="{% url 'accounts:login' %}" class="ml-2">Sign In</a> or <a href="{% url 'accounts:signup' %}"
        class="ml-2">Create An Account</a> to create a post.
    {% endif %}
    <br><br>
    {% if dafitnessapp_list %}
        {% for dafitnessapp in dafitnessapp_list %}
            <article class="post">
                <h2>{{ dafitnessapp.title }}</h2>
                <time class="date">
                    Published By: {{ dafitnessapp.author }}
                    <br>
                    Created Date: {{ dafitnessapp.created_date }}
                </time>
                {% if user == dafitnessapp.author %}
                    {% if user.is_authenticated %}
                        <aside class="actions">
                            <a href="{% url 'dafitnessapp:update' pk=dafitnessapp.pk %}">Edit</a>
                            <a href="{% url 'dafitnessapp:delete' pk=dafitnessapp.pk %}">Delete</a>
                        </aside>
                    {% endif %}
                {% endif %}
                <p>{{ dafitnessapp.text|linebreaksbr }}</p>
            </article>
            <br>
        {% endfor %}
    {% else %}
        <p>No Posts are available.</p>
    {% endif %}
</html>
{% endblock %}

DaFitnessApp/dafitnessapp/templates/dafitnessapp/create.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
<br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    <a href="{% url 'dafitnessapp:comments' %}">
        <input type="button" value="Home" />
    </a>
</form>
{% endblock %}

DaFitnessApp/dafitnessapp/templates/dafitnessapp/delete.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
<br>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the post titled "{{ object.title }}"?</p>
    <form action="{% url 'dafitnessapp:comments' %}">
        <input type="submit" value="Confirm" />
    </form>
    <a href="{% url 'dafitnessapp:comments' %}">
        <input type="button" value="Home" />
    </a>
</form>
{% endblock %}

DaFitnessApp/dafitnessapp/templates/dafitnessapp/home.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
<div class="text-box">
    {% if user.is_authenticated %}
        <h1> Welcome to Da Fitness App, {{request.user}}! <br><br></h1>
    {% else %}
        <h1> Welcome to Da Fitness App! <br><br></h1>
    {% endif %}
    <p>
        This service provides a calculator for how much calories are burned naturally based on your information, as well as
        a calorie tracker where you can fill out how many calories you consume throughout your day.<br>
    </p>
    {% if user.is_authenticated %}
    {% else %}
        Please <a href="{% url 'accounts:login' %}" class="ml-2">Sign In</a> or <a href="{% url 'accounts:signup' %}" class="ml-2">Create An Account</a> to get started.<br><br>
    {% endif %}
</div>
{% endblock %}

DaFitnessApp/dafitnessapp/templates/dafitnessapp/index.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
    <h1>Calculator</h1>
    <script>
        var w, h, a, act, g;
        var outputText;

        function validate() {

            // Get the input from the HTML forms
            g = document.forms["input_form"]["gterm"].value;
            act = document.forms["input_form"]["actterm"].value;
            w = document.forms["input_form"]["wterm"].value;
            h = document.forms["input_form"]["hterm"].value;
            a = document.forms["input_form"]["aterm"].value;
            // Make sure that the information they put are not zero or letters otherwise print a error message

            if (w == 0) {
                outputText = "<em>Weight</em> cannot equal zero!"
            }
            else if (h == 0) {
                outputText = "<em>Height</em> cannot equal zero!"
            }
            else if (a == 0) {
                outputText = "<em>Age</em> cannot equal zero!"
            }
            else if (isNaN(w)) {
                outputText = "<em>Weight</em> must be a number!"
            }
            else if (isNaN(h)) {
                outputText = "<em>Height</em> must be a number!"
            }
            else if (isNaN(a)) {
                outputText = "<em>Age</em> must be a number!"
            }
            else if (g == "m") {
                if (act == 1) {
                    outputText = 1.2 * (65 + (6.2 * w) + (12.7 * h) - (6.8 * a));
                }
                else if (act == 2) {
                    outputText = 1.375 * (65 + (6.2 * w) + (12.7 * h) - (6.8 * a));
                }
                else if (act == 3) {
                    outputText = 1.55 * (65 + (6.2 * w) + (12.7 * h) - (6.8 * a));
                }
                else if (act == 4) {
                    outputText = 1.725 * (65 + (6.2 * w) + (12.7 * h) - (6.8 * a));
                }
                else if (act == 5) {
                    outputText = 1.9 * (65 + (6.2 * w) + (12.7 * h) - (6.8 * a));
                }
                else {
                    outputText = "Error! Please check <em>Question 2</em>"
                }
            }
            else if (g == "f") {
                if (act == 1) {
                    outputText = 1.2 * (655 + (4.2 * w) + (4.3 * h) - (4.7 * a));
                }
                else if (act == 2) {
                    outputText = 1.375 * (655 + (4.2 * w) + (4.3 * h) - (4.7 * a));
                }
                else if (act == 3) {
                    outputText = 1.55 * (655 + (4.2 * w) + (4.3 * h) - (4.7 * a));
                }
                else if (act == 4) {
                    outputText = 1.725 * (655 + (4.2 * w) + (4.3 * h) - (4.7 * a));
                }
                else if (act == 5) {
                    outputText = 1.9 * (655 + (4.2 * w) + (4.3 * h) - (4.7 * a));
                }
                else {
                    outputText = "Error! Please check <em>Question 2</em>"
                }
            }
            else {
                outputText = "Error! Please check <em>Question 1</em>"
            }

            //output the result (or errors)
            document.getElementById("output_text").innerHTML = outputText;
        }
    </script>
    <span>
        Please enter your information below:</p>
    </span>
    <!-- add into .js file later -->
    <!-- Below is the code of how the user puts their information
        The gender and ammount exercises will be filled through a drop down list.
        The Weight, Height and Age will be inputs by typing the numbers in -->
    <form name="input_form" action="javascript:validate();">
        1. Gender (M/F):
        <select id="gterm">
            <option value=""></option>
            <option value="m">Male</option>
            <option value="f">Female</option>
        </select>
        <br><br>
        2. How active are you? On a scale of 1 to 5:
        <select id="actterm">
            <option value=""></option>
            <option value="1">(1) Never exercise</option>
            <option value="2">(2) Exercise 1-3 times a week</option>
            <option value="3">(3) Exercise 3-5 times a week</option>
            <option value="4">(4) Exercise 6-7 times a week</option>
            <option value="5">(5) You are a professional athlete</option>
        </select>
        <br><br>
        3. Weight (lbs): <input type="text" name="wterm" size="5" required>
        <br><br>
        4. Height (in): <input type="text" name="hterm" size="5" required>
        <br><br>
        5. Age (yrs): <input type="text" name="aterm" size="5" required>
        <br><br>
        <input type="submit" value="Calculate">
    </form>
    <p>Calories burned naturally:</p>
    <p id="output_text"></p>
{% endblock %}

DaFitnessApp/dafitnessapp/templates/dafitnessapp/results.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
<html>
    <head>
        <meta name="viewport" content="with=device-width, initial-scale=1.0">
        <title>Da Fitness App</title>
        <!-- bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <!-- allows dropdown menu to work -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@200;300;400;600;700&display=swap" rel="stylesheet">
        <!-- for the close and open button when opening on a mobile device -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- pie chart -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.3/Chart.min.js"></script>
    </head>
    <body onload="CalorieGraph()">
            <h1>Daily Calorie Intake</h1>
            <div class="row">
                <div class="col-md-6 border-right">
                    <script>
                        function CalorieGraph() {//from   w w  w. j  a v  a 2  s . c  o  m
                            var breakfast = document.CalorieForm.Breakfast.value,
                                lunch = document.CalorieForm.Lunch.value,
                                dinner = document.CalorieForm.Dinner.value,
                                snacks = document.CalorieForm.Snacks.value,
                                ctx = document.getElementById('Calorieratio').getContext('2d');
                            var data = {
                                labels: ["Breakfast", "Lunch", "Dinner", "Snacks"],
                                datasets:
                                    [{
                                        data: [breakfast, lunch, dinner, snacks],
                                        backgroundColor: ["#EF0000", "#0000EF", "#0EF000", "#EF0"],
                                        hoverBackgroundColor: ["#FF0000", "#0000FF", "#0FF000", "#FF0"]
                                    }]
                            };
                            var options = {};
                            var myPieChart = new Chart(ctx, {
                                type: 'pie',
                                data: data,
                                options: options
                            });
                        }

                    </script>
                        <!-- Below is the code of how the user puts their calorie intake from meals and snacks -->
                    <form name="CalorieForm" method="post">
                        Please enter the amount of calories consumed below:
                        <br><br>
                        Breakfast: <br><input type="number" name="Breakfast" value=""> cals<br><br>
                        Lunch: <br><input type="number" name="Lunch" value=""> cals<br><br>
                        Dinner: <br><input type="number" name="Dinner" value=""> cals<br><br>
                        Snacks: <br><input type="number" name="Snacks" value=""> cals<br><br>
                        <button type="button" onclick="CalorieGraph();">Generate Pie Chart</button>
                    </form>
                </div>
                <div class="column">
                    <canvas id="Calorieratio" height="225"></canvas>
                </div>
            </div>
        </section>
    </body>
</html>
{% endblock %}

DaFitnessApp/dafitnessapp/templates/dafitnessapp/update.html
{% extends "dafitnessapp/base.html" %}

{% block content %}
<br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'dafitnessapp:delete' dafitnessapp.id %}">
        <input type="button" value="Delete">
    </a>
    <a href="{% url 'dafitnessapp:comments' %}">
        <input type="button" value="Go Back">
    </a>
</form>
{% endblock %}